"""empty message

Revision ID: 8af163873f64
Revises: 
Create Date: 2024-10-12 00:51:42.244865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af163873f64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('day_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('opening_stock', sa.Integer(), nullable=False),
    sa.Column('production', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Integer(), nullable=False),
    sa.Column('manually_entered_closing_stock', sa.Integer(), nullable=True),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('day_record_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_record_id'], ['day_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('night_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('opening_stock', sa.Integer(), nullable=False),
    sa.Column('production', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Integer(), nullable=False),
    sa.Column('manually_entered_closing_stock', sa.Integer(), nullable=True),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('day_record_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_record_id'], ['day_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('night_stocks')
    op.drop_table('day_stocks')
    op.drop_table('day_records')
    # ### end Alembic commands ###
